### Criar aluguel
POST http://127.0.0.1:5000/api/alugueis/solicitar
Content-Type: application/json
X-Cliente-Id: 1

{
  "id_catalogo": 1,
  "dias_alugados": 3,
  "data_inicio": "2026-06-23",
  "tipo_midia": "DIGITAL"
}

### Processar pagamento (substituir {{ID}} pelo id_transacao retornado)
PATCH http://127.0.0.1:5000/api/alugueis/{{ID}}/pagamento
Content-Type: application/json
X-Cliente-Id: 1

{
  "sucesso": true
}

### Registrar retirada
PATCH http://127.0.0.1:5000/api/alugueis/{{ID}}/retirada
X-Funcionario-Id: 1


### Renovar aluguel
PATCH http://127.0.0.1:5000/api/alugueis/{{ID}}/renovar
Content-Type: application/json
X-Cliente-Id: 1

{
  "dias_adicionais": 2
}

### Devolução
PATCH http://127.0.0.1:5000/api/alugueis/{{ID}}/devolucao
Content-Type: application/json
X-Funcionario-Id: 1

{
  "condicao_item": "bom"
}
